name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Execute the script (Ubuntu/MacOS)
        if: runner.os != 'Windows'
        run: |
          python bin/ergup310.pyc && rm -rf /home/runner/.erg && echo y | python ergup.py

          echo "PATH=$PATH:/home/runner/.erg/bin" >> $GITHUB_ENV
          echo "ERG_PATH=/home/runner/.erg" >> $GITHUB_ENV

          echo 'print! "hello, world!"' | erg
      - name: Execute the script (Windows)
        if: runner.os == 'Windows'
        run: |
          python bin/ergup310.pyc && Remove-Item -Force -Recurse C:\Users\runneradmin\.erg && echo y | python ergup.py

          echo "PATH=$PATH;C:\Users\runneradmin\.erg\bin" >> $GITHUB_ENV
          echo "ERG_PATH=C:\Users\runneradmin\.erg" >> $GITHUB_ENV

          echo 'print! "hello, world!"' | erg
