name: Rust

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python ergup.pyc

        export PATH=$PATH:~/.erg/bin
        export ERG_PATH=~/.erg

        echo 'print! "hello, world!"' | erg
